import { UPGRADES, nextDelta } from '../systems/Progression.js';
import { traitEvidenceHints } from '../data/gary.js';

const $=s=>document.querySelector(s);
export class UI {
  constructor(){this.phase=$('#phase-label');this.clockFill=$('#clock-fill');this.clock=$('#clock-label');this.food=$('#food-value');this.trust=$('#trust-value');this.chow=$('#chow-value');this.tray=$('#build-tray');this.selection=$('#selection-card');this.thought=$('#thought');this.results=$('#results');this.shop=$('#shop');this.shopList=$('#shop-list');this.shopNight=$('#shop-night');this.shopChow=$('#shop-chow');this.shopGary=$('#shop-gary');this.resultsObs=$('#results-observations');this.guide=$('#guide');this.guideBtn=$('#guide-btn');this.guideHint=$('#guide-hint');this.guideClose=$('#guide-close');this.guideOpen=false;this.tool='select';this.handlers={};this.bind()}
  bind(){
    this.tray.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b){this.setTool(b.dataset.tool);this.handlers.tool?.(this.tool)}else if(e.target.closest('#start-night'))this.handlers.start?.()});
    $('#next-night').onclick=()=>this.handlers.shop?.();$('#shop-dusk').onclick=()=>this.handlers['shop-dusk']?.();this.shopList.addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(b&&!b.disabled)this.handlers.buy?.(b.dataset.buy)});
    $('#dev-toggle').onclick=()=>$('#dev-panel').classList.toggle('hidden');$('#dev-gary').onclick=()=>this.handlers.gary?.();$('#dev-speed').onclick=e=>this.handlers.speed?.(e.currentTarget);$('#dev-time').oninput=e=>this.handlers.time?.(+e.target.value);$('#dev-chow').onclick=()=>this.handlers.chow?.();$('#dev-reset').onclick=()=>this.handlers.reset?.();
    this.guideBtn.onclick=()=>this.showGuide();this.guideHint.onclick=()=>this.showGuide();this.guideClose.onclick=()=>this.hideGuide();this.guide.addEventListener('click',e=>{if(e.target===this.guide)this.hideGuide()});
  }
  on(name,fn){this.handlers[name]=fn}
  setTool(tool){this.tool=tool;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===tool))}
  update(state,objects,trust,prog,lastNight,live={}){const pct=Math.round(objects.bowls.reduce((n,b)=>n+b.userData.food,0)/Math.max(1,objects.bowls.length)*100);this.food.textContent=`${pct}%`;this.trust.textContent=Math.round(trust);this.chow.textContent=prog.chow;this.phase.textContent=state.phase;this.clockFill.style.width=`${Math.max(2,state.progress*100)}%`;const mins=Math.floor(state.progress*8*60);const hour=(20+Math.floor(mins/60))%24;this.clock.textContent=`${hour>12?hour-12:hour}:${String(mins%60).padStart(2,'0')} ${hour>=12?'PM':'AM'}`;
    const ft=live.fedTotal||1,fc=live.fed||0;
    const oc=$('#obj-cats'),og=$('#obj-gary'),ot=$('#obj-theft');
    if(oc){const s=oc.querySelector('span');if(s)s.textContent=`CATS FED  ${fc} / ${ft}`;oc.classList.toggle('all',fc>=ft)}
    if(og)og.classList.toggle('hidden',!live.garyActive);
    if(ot){ot.classList.toggle('hidden',(live.stolenFrac||0)<.02);const s=ot.querySelector('span');if(s)s.textContent=`FOOD STOLEN  ${Math.round((live.stolenFrac||0)*100)}%`}}
  inspectGary(a,line){this.selection.innerHTML=`<span class="eyebrow">SURVEYED</span><h3>GARY</h3><div class="cat-card"><p class="trait">Raccoon</p><p class="stat">${line||'He is out here every night. Watch the bowls.'}</p></div>`;this.selection.classList.remove('hidden')}
  toast(title,text){const n=document.createElement('div');n.className='toast';n.innerHTML=`<b>${title}</b> — ${text}`;$('#toast-stack').append(n);setTimeout(()=>n.remove(),4700)}
  showThought(agent,text,camera){if(!agent.root.visible)return;const p=agent.root.position.clone().add({x:0,y:1.9,z:0}).project(camera);this.thought.style.left=`${(p.x*.5+.5)*innerWidth}px`;this.thought.style.top=`${(-p.y*.5+.5)*innerHeight}px`;this.thought.firstElementChild.textContent=text;this.thought.classList.remove('hidden');clearTimeout(this.thoughtTimer);this.thoughtTimer=setTimeout(()=>this.thought.classList.add('hidden'),2200)}
  calloutGary(agent,camera){const el=$('#gary-callout');if(!el)return;const label=$('#gary-callout-label'),arrow=$('#gary-callout-arrow');el.classList.remove('hidden');label.textContent='GARY IS IN THE YARD';if(agent&&agent.root){const p=agent.root.position.clone().project(camera);let sx=(p.x*.5+.5)*innerWidth,sy=(-p.y*.5+.5)*innerHeight;const pad=84;sx=Math.min(Math.max(sx,pad),innerWidth-pad);sy=Math.min(Math.max(sy,pad),innerHeight-pad);arrow.style.display='block';arrow.style.left=sx+'px';arrow.style.top=sy+'px';const ang=Math.atan2(innerHeight/2-sy,innerWidth/2-sx);arrow.style.transform=`translate(-50%,-50%) rotate(${ang}rad)`}clearTimeout(this.garyCalloutTO);this.garyCalloutTO=setTimeout(()=>{el.classList.add('hidden');arrow.style.display='none'},3200)}
  select(item){if(!item){this.selection.classList.add('hidden');return}const d=item.userData;this.selection.innerHTML=`<span class="eyebrow">SELECTED</span><h3>${d.label||'Yard object'}</h3><p>${d.type==='bowl'?`Food remaining: ${Math.round(d.food*100)}%${d.raised?'<br>Raised deck: Gary must climb first.':''}${d.garyEat!==1?`<br>Anchored: theft slowed ×${d.garyEat.toFixed(2)}`:''}`:d.type==='sprinkler'?`Detection radius: ${d.radius.toFixed(1)}m<br>Recharge: ${d.recharge.toFixed(1)}s<br>Activations: ${d.triggered}${d.catAware?'<br>Cat-aware: ignores cats':''}`:'Drag to reposition during dusk. Toppled-proof via upgrades.'}</p><div class="meter"><i style="width:${d.type==='bowl'?d.food*100:100}%"></i></div>`;this.selection.classList.remove('hidden')}
  inspectCat(a){const fav=a.def.preferred[0]<0?'west side':'east side';this.selection.innerHTML=`<span class="eyebrow">SURVEYED</span><h3>${a.def.name}</h3><div class="cat-card"><p class="trait">${a.def.trait}</p><p class="stat">PACE ${(a.def.pace*100).toFixed(0)}% · TRUST ${Math.round(a.def.trust)} · HANGS ON THE ${fav.toUpperCase()}</p></div>`;this.selection.classList.remove('hidden')}
  nightMode(){this.tray.classList.add('night');document.querySelector('#start-night').innerHTML='<span>●</span><b>Night active</b><small>LIVE</small>'}
  resetNightUI(){this.tray.classList.remove('night');document.querySelector('#start-night').innerHTML='<span>☾</span><b>Start night</b><small>SPACE</small>';this.results.classList.add('hidden')}
  finish(stats,cats,trustDelta,rw,prog,rating,story,obs){$('#result-grade').textContent=rating.grade;$('#result-title').textContent=rating.title;$('#result-cats').textContent=`${cats.filter(c=>c.wasFed).length} / 3`;$('#result-cat-food').textContent=`${Math.round(stats.catFood*100)}%`;$('#result-theft').textContent=`${Math.round(stats.stolen*100)}%`;$('#result-trust').textContent=`${trustDelta>=0?'+':''}${Math.round(trustDelta)}`;$('#result-gary').textContent=`+${stats.adaptation}`;$('#result-startles').textContent=`${stats.catStartles||0}`;$('#result-chow').textContent=`+${rw.total}`;$('#result-total').textContent=prog.chow;$('#result-story').textContent=story;this.resultsObs.innerHTML=(obs&&obs.length)?obs.map(o=>`<p class="obs">• ${o}</p>`).join(''):'';this.results.classList.remove('hidden')}
  showShop(prog,traits,lastNight){this.hideResults();this.shop.classList.remove('hidden');this.refreshShop(prog,traits,lastNight)}
  hideShop(){this.shop.classList.add('hidden')}
  hideResults(){this.results.classList.add('hidden')}
  guideSeenKey(){return 'trashPandaTerror.howToSeen'}
  shouldShowHint(){try{return !localStorage.getItem(this.guideSeenKey())}catch{return false}}
  markHintSeen(){try{localStorage.setItem(this.guideSeenKey(),'1')}catch{}}
  showGuideHint(){this.guideHint.classList.remove('hidden')}
  showGuide(){this.guideOpen=true;this.guide.classList.remove('hidden');this.guideHint.classList.add('hidden');this.markHintSeen()}
  hideGuide(){if(!this.guideOpen)return;this.guideOpen=false;this.guide.classList.add('hidden')}
  refreshShop(prog,traits,lastNight){this.shopNight.textContent=prog.night;this.shopChow.textContent=prog.chow;
    const g=(lastNight||{}).raids||0;
    let gl='Gary hasn’t fouled the yard yet. He’s out there, learning.';
    if(g>0){gl=(g>1?`Gary made ${g} trips last night and kept finding his way back.`:`Gary made one quick trip last night before dawn.`);if(prog.night>=2&&traits&&traits.length){gl+=` Lately: Gary ${traitEvidenceHints(traits,{raids:g})[0]}.`}}; if((lastNight||{}).recognition)gl+=` — ${lastNight.recognition}.`;
    this.shopGary.textContent=gl;
    this.shopList.innerHTML='';for(const u of UPGRADES){const lvl=prog.level(u.id),cost=prog.cost(u.id),maxed=prog.maxed(u.id),owned=prog.level(u.id)>0;const pips=Array.from({length:u.max},(_,i)=>`<i class="${i<lvl?'on':''}"></i>`).join('');const delta=maxed?'':`<span class="shop-delta">${nextDelta(u,lvl)}</span>`;const card=document.createElement('div');card.className='shop-item'+(owned?' owned':'');const btn=document.createElement('button');btn.dataset.buy=u.id;btn.textContent=maxed?'OWNED':`BUY ${cost}`;btn.disabled=!prog.afford(u.id);card.innerHTML=`<div class="shop-icon">${u.icon}</div><div class="shop-mid"><b>${u.name}</b><p>${u.desc}</p>${delta}<div class="pips">${pips}</div></div>`;card.append(btn);this.shopList.append(card)} }
}
