import * as THREE from 'three';
import { CATS, GARY } from '../systems/Tuning.js';
import { behaviorOf } from '../data/gary.js';

const mat=(c,r=.85)=>new THREE.MeshStandardMaterial({color:c,roughness:r});
const lerp=THREE.MathUtils.lerp;
function ellipsoid(radius,color,scale){const m=new THREE.Mesh(new THREE.SphereGeometry(radius,14,10),mat(color));m.scale.set(...scale);m.castShadow=true;return m}

function makeAnimal(def,isRaccoon=false){
  const root=new THREE.Group(),rig=new THREE.Group();root.add(rig);
  const R=isRaccoon,flash=[],mark=m=>{flash.push(m);return m};
  const SILVER=0xb8bdb8,DARK=0x26292b,FOOT=0x3a3d3c,MASKCOL=0x161817;
  // BODY: cats slim + higher carriage; Gary broad, low, heavy-rumped
  const body=mark(ellipsoid(.55,def.coat,R?[1.62,.66,1.95]:[.9,.74,1.5]));body.position.y=R?.5:.6;rig.add(body);
  // HEAD: Gary big & round; cats compact
  const head=mark(ellipsoid(.4,def.coat,R?[1.05,.9,1.02]:[.82,.92,.9]));head.position.set(0,.87,.62);rig.add(head);
  // MUZZLE + nose: Gary light, broad snout
  const muzzle=mark(ellipsoid(.19,R?0xc2c7c2:def.accent,R?[1.05,.68,.95]:[.85,.62,.8]));muzzle.position.set(0,R?.8:.78,R?.98:.96);rig.add(muzzle);
  const nose=mark(ellipsoid(.075,0x111412,[1,.7,.8]));nose.position.set(0,R?.84:.83,R?1.15:1.09);rig.add(nose);
  // EYES: bigger + brighter on Gary so he reads instantly in the dark (kept out of the flash list)
  for(const x of [-.2,.2]){const eye=ellipsoid(R?.06:.047,R?0xe8ec9a:0xafd46e,[1,1,.5]);eye.material.emissive=new THREE.Color(eye.material.color);eye.material.emissiveIntensity=.9;eye.position.set(x*(R?.68:.7),R?.98:.95,R?.97:.95);rig.add(eye)}
  // EARS: Gary = rounded knobs; cats = pointed cones
  const ears=[];for(const x of (R?[-.25,.25]:[-.22,.22])){let ear;if(R){ear=mark(ellipsoid(.13,def.coat,[.62,.34,.58]));ear.position.set(x,1.11,.5)}else{ear=mark(new THREE.Mesh(new THREE.ConeGeometry(.15,.4,8),mat(def.coat)));ear.position.set(x,1.19,.55)}ear.castShadow=true;ear.rotation.z=x>0?-.13:.13;rig.add(ear);ears.push(ear)}
  // GARY black mask + pale brows/moustache => silhouette reads as raccoon from across the yard
  if(R){const mask=mark(ellipsoid(.32,MASKCOL,[1.32,.42,.62]));mask.position.set(0,.94,.82);mask.renderOrder=-1;rig.add(mask);const bl=mark(ellipsoid(.05,0xe6e9e4,[1.25,.62,1]));bl.position.set(-.2,1.03,.9);rig.add(bl);const br=mark(ellipsoid(.05,0xe6e9e4,[1.25,.62,1]));br.position.set(.2,1.03,.9);rig.add(br)}
  // LEGS: Gary short + wide stance; cats long
  const legs=[],legH=R?.72:1.28;for(const x of (R?[-.44,.44]:[-.33,.33]))for(const z of [-.36,.37]){const leg=mark(ellipsoid(.13,R?FOOT:def.coat,[.8,legH,.8]));leg.position.set(x,.25,z);rig.add(leg);legs.push(leg)}
  // TAIL: Gary = thick, huge, heavily ringed; cats = slim
  const tail=new THREE.Group();if(R){for(let i=0;i<8;i++){const seg=mark(ellipsoid(.3-i*.022,i%2?DARK:SILVER,[.92,.95,1.02]));seg.position.set(0,.03+i*.03,-i*.3);tail.add(seg)}}else{for(let i=0;i<5;i++){const seg=mark(ellipsoid(.18-i*.012,def.coat,[1,1,1.55]));seg.position.set(0,.05+i*.03,-i*.25);tail.add(seg)}}tail.position.set(0,.62,-.7);rig.add(tail);
  root.userData={rig:{rig,head,tail,legs,ears},flashMeshes:flash};return root;
}

export class Agent {
  constructor(def,type,scene,persistent={}){this.def={...def,...persistent};this.type=type;this.root=makeAnimal(this.def,type==='raccoon'||type==='kit');this.root.userData.agent=this;this.root.position.set(def.approach[0],0,def.approach[1]);this.root.visible=false;scene.add(this.root);this.state='waiting';this.target=null;this.fear=0;this.fed=0;this.wasFed=false;this.memory=Object.assign({sprinkler:0,hose:0,barrier:0,raised:0,light:0},persistent.memory||{});this.traits=persistent.traits||[];this.personality=behaviorOf(this.traits);if(type==='kit'){this.root.scale.setScalar(.6);Object.assign(this.personality,{fearMult:def.fearMult||1.6,appetite:def.appetite||.5,fedTarget:def.fedTarget||.12})}this.pose={crouch:0,headUp:0,tailUp:0,earsIn:0,lean:0,headPan:0};this.poseY=1;this.speed=type==='raccoon'?1.25:(type==='kit'?1.7:1.05);this.scene=scene;this.nextDecision=0;this.active=false;this.bumpCd=0;this.stepTimer=0;this.hopT=0;this.tugT=0}
  p(name){return this.personality[name]}
  flashHit(){this._flash=1.15}
  reset(){this.state='waiting';this.target=null;this.fear=0;this.fed=0;this.wasFed=false;this.active=false;this.root.visible=false;this.delay=0;this.wander=null;this.climbedNow=false;this.boundaryPokes=0;this.lightTriggered=false;this.lastSprayedAt=-99;this.bumpCd=0;this.stepTimer=0;this.hopT=0;this.tugT=0;this.lastStartle=-99;this.sprinklerDanger=[];this.fedGoal=this.type==='cat'?CATS.feedNeeded:(this.type==='kit'?(this.p('fedTarget')||0.12):(this.p('fedTarget')||GARY.fedTarget))}
  spawn(delay=0,from=null){this.delay=delay;this.active=true;this.root.visible=false;this.state='arriving';if(from){this.root.position.set(from[0],0,from[1])}}
  setPose(t){const P=this.pose,a=t||{};P.crouch=lerp(P.crouch,a.crouch??0,.12);P.headUp=lerp(P.headUp,a.headUp??0,.12);P.tailUp=lerp(P.tailUp,a.tailUp??0,.12);P.earsIn=lerp(P.earsIn,a.earsIn??0,.16);P.lean=lerp(P.lean,a.lean??0,.12);P.headPan=lerp(P.headPan,a.headPan??0,.12);const rig=this.root.userData.rig,cr=1-P.crouch*.28;this.poseY=cr;rig.rig.scale.set(cr,1+P.crouch*.14,cr);rig.rig.rotation.x=P.lean*-.5;rig.head.position.y=.87+.18*P.headUp;rig.head.rotation.y=P.headPan;rig.tail.rotation.x=-.25-.32*P.tailUp;rig.ears.forEach(e=>e.rotation.z=(e.position.x>0?-.13:.13)-P.earsIn);const f=this._flash||0;if(this.root.userData.flashMeshes){const col=this.type==='raccoon'?0x6fb4ff:0xff8f47;for(const m of this.root.userData.flashMeshes){if(m.material&&m.material.emissive){if(f>0.02){m.material.emissive.setHex(col);m.material.emissiveIntensity=Math.min(1.2,f)}else m.material.emissiveIntensity=0}}}}
  fleeFrom(point,amount=1,distScale=1,dirOverride=null){if(this.type==='raccoon'){const resist=this.p('startleResist')||0;let a=amount*(1-resist);if(this.memory.hose>1)a*=Math.max(.5,1-this.memory.hose*.03);amount=Math.max(.2,a)}amount*=this.p('fearMult')||1;this.fear=Math.max(this.fear,amount);this.state='fleeing';let d;if(dirOverride){d=dirOverride.clone().setY(0)}else{d=this.root.position.clone().sub(point).setY(0)}if(d.lengthSq()<0.0001)d.set(0,0,1);d.normalize();this.target=d.multiplyScalar(8*Math.max(1,distScale)).add(this.root.position);this.target.x=THREE.MathUtils.clamp(this.target.x,-15,15);this.target.z=THREE.MathUtils.clamp(this.target.z,-7,13)}
  rememberSprinkler(sp){if(!sp)return;const x=sp.position.x,z=sp.position.z,R=sp.userData.radius||4;const ex=this.sprinklerDanger.find(h=>Math.abs(h.x-x)<.01&&Math.abs(h.z-z)<.01);if(ex){ex.hits++;ex.radius=R}else this.sprinklerDanger.push({x,z,radius:R,hits:1})}
  hazardAvoidMul(){return .5+.7*this.def.skittishness}
  catHazardPenalty(target){let p=0;const ax=this.root.position.x,az=this.root.position.z,bx=target.x,bz=target.z,abx=bx-ax,abz=bz-az,len2=abx*abx+abz*abz;for(const h of this.sprinklerDanger){let t=len2>0?((h.x-ax)*abx+(h.z-az)*abz)/len2:0;t=THREE.MathUtils.clamp(t,0,1);const cx=ax+abx*t,cz=az+abz*t,dd=Math.hypot(cx-h.x,cz-h.z),pr=h.radius*(0.7+0.45*h.hits)+this.hazardAvoidMul();if(dd<pr)p+=9*(1+(h.hits-1)*0.4)}return p}
  pickCatBowl(ctx){let best=null,bs=Infinity;for(const b of ctx.objects.bowls){if(b.userData.food<=.005)continue;const score=b.position.distanceTo(this.root.position)+this.catHazardPenalty(b.position);if(score<bs){bs=score;best=b}}return best||ctx.objects.getNearestBowl(this.root.position).bowl}
  steerFor(target,ctx){const P=this.root.position,dir=target.clone().sub(P);dir.y=0;const dl=dir.length();const base=dl>0.001?dir.normalize():new THREE.Vector3(0,0,1);for(const h of this.sprinklerDanger){const c=new THREE.Vector3(h.x,0,h.z),toP=P.clone().sub(c),d=toP.length(),avoid=h.radius*(0.75+0.45*h.hits)+this.hazardAvoidMul();if(d<avoid&&d>0.001){const away=toP.normalize();base.addScaledVector(away,((avoid-d)/avoid)*1.3);const toT=target.clone().sub(c);toT.y=0;const side=new THREE.Vector3(-toT.z,0,toT.x);if(side.dot(toP)<0)side.negate();base.addScaledVector(side,(avoid-d)*0.5)}}base.y=0;return base.lengthSq()>0.0001?base.normalize():new THREE.Vector3(0,0,1)}
  moveToward(target,dt,barriers=[],ctx){const d=target.clone().sub(this.root.position);d.y=0;const dist=d.length();if(dist>.05){d.normalize();let pushed=false;for(const b of barriers){const away=this.root.position.clone().sub(b.position).setY(0),bd=away.length();const R=b.userData.blockRadius||1.65,str=b.userData.blockStrength||1.8;if(bd<R&&bd>.01){pushed=true;away.normalize();const side=new THREE.Vector3(-d.z,0,d.x);if(side.dot(away)<0)side.negate();d.addScaledVector(side,(R-bd)*str)}}if(pushed&&this.type==='raccoon'){this.memory.barrier=(this.memory.barrier||0)+.05;if(this.bumpCd<=0){this.bumpCd=.5;this.justBumped=1}}this.bumpCd=Math.max(0,this.bumpCd-dt);d.normalize();const boost=this.fear>GARY.boostFear-(this.p('sprintCommit')?0.15:0)?1.75:1;const pace=this.speed*boost;this.root.position.addScaledVector(d,Math.min(dist,pace*dt));this.root.rotation.y=lerp(this.root.rotation.y,Math.atan2(d.x,d.z),dt*6);const rig=this.root.userData.rig;const sprint=boost>1.3;const bob=(sprint?Math.abs(Math.sin(performance.now()*.014*pace))*.05:Math.abs(Math.sin(performance.now()*.010*pace))*.04);const hop=this.hopT>0?Math.sin(this.hopT*14)*.14:0;if(this.type==='raccoon'){rig.rig.position.y=(this.poseY||.9)*.9+bob*.5+hop;rig.rig.rotation.z=Math.sin(performance.now()*.011*pace)*.11;}else{rig.rig.position.y=this.poseY+bob+hop;rig.rig.rotation.z=(this.anchoredEat?Math.sin(performance.now()*.03)*.04:0);}rig.legs.forEach((l,i)=>l.rotation.x=Math.sin(performance.now()*.011*pace+i*Math.PI)*(sprint?.45:.3));rig.tail.rotation.x=-.25-.2*boost-(sprint?.25:0)+Math.sin(performance.now()*.006)*.1;if(this.stepTimer<=0&&ctx)this.stepTimer=.36+Math.random()*.08;}return dist}
  update(dt,ctx){if(this._flash>0)this._flash=Math.max(0,this._flash-dt*1.5);if(!this.active)return;if(this.delay>0){this.delay-=dt;return}this.root.visible=true;if(this.stepTimer>0){this.stepTimer-=dt;if(this.stepTimer<=0)ctx.onStep&&ctx.onStep(this)}if(this.hopT>0)this.hopT-=dt;this.fear=Math.max(0,this.fear-dt*GARY.fearDecay*(this.p('fearRecovery')||1));if(this.justBumped){this.justBumped=0;if(ctx.onBarrier&&this.type==='raccoon')ctx.onBarrier(this)}if(this.type==='cat')this.updateCat(dt,ctx);else if(this.type==='kit')this.updateKit(dt,ctx);else this.updateRaccoon(dt,ctx)}
  updateCat(dt,ctx){
    if(this.state==='arriving'){this.target=new THREE.Vector3(this.def.preferred[0],0,this.def.preferred[1]);this.state='seeking'}
    if(this.state==='fleeing'){this.setPose({tailUp:.7,earsIn:.5,lean:.4});if(this.moveToward(this.target,dt,ctx.objects.barriers,ctx)<.2){this.state='hesitating';this.nextDecision=(1+this.def.skittishness)*1.1+Math.random()*1.3}return}
    if(this.state==='hesitating'){this.nextDecision-=dt;if(this.nextDecision<=0){this.state='seeking';this.wander=null;const n=ctx.objects.getNearestBowl(this.root.position);this.target=n.bowl?.position.clone()||new THREE.Vector3(...this.def.approach)}return}
    if(this.state==='seeking'&&!this.wander&&this.def.curiosity>.6&&Math.random()<dt*.12){this.wander=this.root.position.clone().add(new THREE.Vector3((Math.random()-.5)*8,0,(Math.random()-.5)*8));this.wander.x=THREE.MathUtils.clamp(this.wander.x,-13,13);this.wander.z=THREE.MathUtils.clamp(this.wander.z,-6,11)}
    if(this.wander){if(this.moveToward(this.wander,dt,ctx.objects.barriers,ctx)<.35){this.wander=null}return}
    const bowl=this.pickCatBowl(ctx);if(!bowl){this.state='leaving';this.target=new THREE.Vector3(this.def.approach[0],0,this.def.approach[1])}
    else if(this.state!=='eating'){this.target=bowl.position.clone();this.state='seeking'}
    if(this.state==='seeking'){this.setPose({lean:.35,crouch:.1});const steer=this.steerFor(bowl.position,ctx),way=this.root.position.clone().add(steer);this.moveToward(way,dt,ctx.objects.barriers,ctx);if(this.root.position.distanceTo(bowl.position)<0.72){this.state='eating';this.target=bowl;if(bowl.userData.raised)this.hopT=.32;ctx.onBowl&&ctx.onBowl(this)}}
    if(this.state==='eating'){this.setPose({crouch:.28});if(this.nextDecision<=0){this.nextDecision=1;ctx.onMunch&&ctx.onMunch(this)}const used=ctx.objects.consume(this.target,dt*CATS.baseEat*(this.def.pace||1),'cat',ctx.stats);this.fed+=used;if(used<=0||this.fed>CATS.feedNeeded){this.state='leaving';this.target=new THREE.Vector3(this.def.approach[0],0,this.def.approach[1]);if(!this.wasFed){this.wasFed=true;ctx.onFed(this)}}}
    if(this.state==='leaving'){this.setPose({});this.moveToward(this.target,dt,ctx.objects.barriers,ctx)}
  }
  pickBowl(ctx){const nearest=ctx.objects.getNearestBowl(this.root.position).bowl;const bars=ctx.objects.barriers;if(!bars.length||this.memory.barrier<2)return nearest;let best=null,bs=Infinity;for(const b of ctx.objects.bowls){if(b.userData.food<=.005)continue;let penalty=0;for(const bar of bars){if(b.position.distanceTo(bar.position)<((bar.userData.blockRadius||1.65)*2.2))penalty+=7}const score=b.position.distanceTo(this.root.position)+penalty;if(score<bs){bs=score;best=b}}if(best&&best!==nearest)this.justRerouted=1;return best||nearest}
  updateKit(dt,ctx){
    if(this.state==='arriving'){this.state='seeking'}
    if(this.state!=='fleeing'&&this.state!=='leaving'&&this.state!=='probing'){
      const tr=ctx.objects.sprinklers[0];
      if(tr&&tr.userData.cooldown<=0){const R=tr.userData.radius||4,d=this.root.position.distanceTo(tr.position);
        if(d<R){ctx.objects.triggerSprinkler(tr);this.memory.sprinkler+=1;this.fleeFrom(tr.position,1.6);this.rememberSprinkler(tr);ctx.onSprayed(this,false);return}
        if((this.memory.sprinkler||0)===0&&d<R+2.5&&Math.random()<dt*1.1){this.state='probing';this.nextDecision=.5;this.testSpr=tr}}
      const bowl=ctx.objects.getNearestBowl(this.root.position).bowl;
      if(bowl){this.state='seeking';this.moveToward(bowl.position,dt,ctx.objects.barriers,ctx);if(this.root.position.distanceTo(bowl.position)<.72){this.state='eating';this.target=bowl}}
      else this.state='leaving';
    }
    if(this.state==='probing'){this.setPose({crouch:.5,headPan:Math.sin(performance.now()*.006)*.5});this.nextDecision-=dt;if(this.nextDecision<=0)this.state='seeking'}
    if(this.state==='eating'){this.setPose({crouch:.32});const used=ctx.objects.consume(this.target,dt*CATS.baseEat*(this.p('appetite')||.5),'raccoon',ctx.stats);this.fed+=used;if(used<=0||this.fed>this.fedGoal){this.state='leaving';this.target=this.panicBolt();ctx.onKitTheft(this)}}
    if(this.state==='fleeing'){this.setPose({tailUp:.9,earsIn:.6});if(this.moveToward(this.target,dt,ctx.objects.barriers,ctx)<.3){this.state='leaving';this.target=this.panicBolt()}}
    if(this.state==='leaving'){this.setPose({lean:.3});if(this.moveToward(this.target,dt,ctx.objects.barriers,ctx)<.4){this.state='gone';this.active=false;this.root.visible=false;ctx.onKitLeft(this)}}
  }
  panicBolt(){const side=Math.random()<.5?-1:1;return new THREE.Vector3(side*(11+Math.random()*3),0,7+Math.random()*4)}
  updateRaccoon(dt,ctx){
    if(this.state==='arriving'){this.state='watching';this.nextDecision=.6+(this.p('watch')||0)*.4+Math.random()*.4;ctx.onGarySeen(this)}
    if(this.state==='watching'){this.setPose({crouch:.65,headUp:.55,headPan:Math.sin(performance.now()*.004)*.35});this.nextDecision-=dt;if(this.nextDecision>0)return;this.state='seeking';this.target=this.pickBowl(ctx)?.position.clone()||new THREE.Vector3(0,0,0)}
    if(this.justRerouted){this.justRerouted=0;ctx.onReroute&&ctx.onReroute(this)}
    if(ctx.effects.motionLight&&this.state!=='leaving'){if(!this.lightTriggered){this.lightTriggered=true;ctx.onLight(this)}if(this.state==='eating'&&Math.random()<dt*.25)this.memory.light+=1}
    if(this.state!=='leaving'&&this.state!=='fleeing'&&this.state!=='eating'&&this.state!=='climbing'){
      const savvy=this.memory.sprinkler||0,tr=ctx.objects.sprinklers[0];
      if(tr){const R=tr.userData.radius||4,dist=this.root.position.distanceTo(tr.position),learnAt=this.p('adaptRate')>1?1:2;
        if(dist<R&&tr.userData.cooldown<=0){ctx.objects.triggerSprinkler(tr);this.memory.sprinkler+=(this.p('adaptRate')||1);ctx.stats.adaptation+=1;ctx.onSprayed(this,false);this.fleeFrom(tr.position,this.memory.sprinkler>=3?0.5:1);return}
        if(savvy>=learnAt&&tr.userData.cooldown<=0&&dist<R+Math.min(2,.6+savvy*.2)&&(this.state==='seeking')){this.state='testing';this.nextDecision=(1.0+(this.p('probe')||0))+Math.random()*.6;this.testSpr=tr;this.boundaryPokes=(this.boundaryPokes||0)+1;const away=this.root.position.clone().sub(tr.position).setY(0).normalize();this.target=tr.position.clone().add(away.multiplyScalar(R*.5));ctx.onProbe&&ctx.onProbe(this)}
      }
    }
    if(this.state==='climbing'){this.setPose({crouch:.2,headUp:.5,lean:.15});this.nextDecision-=dt;const b=this.target;if(b&&b.userData&&b.userData.raised&&Math.random()<dt*2&&!this.climbedNow){this.climbedNow=true;this.memory.raised+=1;ctx.onClimb(this)}if(this.nextDecision<=0){if(b?.userData?.food>.005){this.state='eating'}else{this.state='seeking';this.target=this.pickBowl(ctx)?.position.clone()}}return}
    if(this.state==='testing'){this.setPose({crouch:.7,headUp:.5,headPan:Math.sin(performance.now()*.005)*.4});this.nextDecision-=dt;this.moveToward(this.target,dt);if(this.nextDecision<=0){const tr=this.testSpr;const cap=4+(this.p('probeMax')||0);if(tr&&tr.userData.cooldown<=0&&(this.boundaryPokes||0)<cap&&!(this.p('bold')||0)){this.nextDecision=.7;this.boundaryPokes+=1}else{this.boundaryPokes=0;this.state='seeking'}}return}
    if(this.state==='fleeing'){this.setPose({crouch:.5,tailUp:.9,earsIn:.5,lean:.3});if(this.moveToward(this.target,dt,ctx.objects.barriers,ctx)<.3||this.fear<GARY.boostFear){this.state='hesitating';const savvy=this.memory.hose||0;this.nextDecision=Math.max(.6,(1.5+Math.random()*2)-(savvy*0.4));this.flank=null}return}
    if(this.state==='hesitating'){this.nextDecision-=dt;if(this.nextDecision<=0){const flankChance=this.p('flank')||.4;if((this.memory.hose||0)>=(this.p('preferCover')?1:2)&&Math.random()<flankChance){this.state='flanking';this.flank=this.root.position.clone().add(new THREE.Vector3((Math.random()-.5)*10,0,6+Math.random()*4));this.flank.x=THREE.MathUtils.clamp(this.flank.x,-13,13);this.flank.z=THREE.MathUtils.clamp(this.flank.z,2,12)}else{this.state='watching';this.nextDecision=Math.max(.3,(this.p('watch')||0)*.4)}}return}
    if(this.state==='flanking'){this.setPose({crouch:.85,lean:.2});if(this.moveToward(this.flank,dt,ctx.objects.barriers,ctx)<.4){this.state='seeking';this.target=this.pickBowl(ctx)?.position.clone();ctx.onCover(this)}return}
    const nearest=this.pickBowl(ctx);if(!nearest){this.state='leaving';this.target=new THREE.Vector3(-11,0,7)}else if(this.state!=='eating'&&this.state!=='climbing'&&this.state!=='testing'&&this.state!=='leaving'){this.target=nearest.position.clone();this.state='seeking'}
    if(this.state==='seeking'){this.setPose({lean:.5,crouch:.12});if(this.moveToward(this.target,dt,ctx.objects.barriers,ctx)<.85){if(nearest.userData.raised&&ctx.effects.platformPause>0){this.state='climbing';this.nextDecision=Math.max(.2,(ctx.effects.platformPause||0)-(this.memory.raised||0)*.35);this.climbedNow=false;this.target=nearest;ctx.onTheft(this)}else{this.state='eating';this.target=nearest;ctx.onTheft(this)}}}
    if(this.state==='eating'){const anchored=this.target.userData.garyEat<0.95;this.anchoredEat=anchored;this.setPose(anchored?{crouch:.3,lean:.2}:{crouch:.25});if(anchored){this.tugT-=dt;if(this.tugT<=0){this.tugT=.5+Math.random()*.2;ctx.onAnchored&&ctx.onAnchored(this)}}const lightMult=ctx.effects.motionLight?Math.max(.55,1-Math.min(.2,.06+this.memory.light*.005)):1;const appetiteBase=GARY.appetiteBase*(1+Math.max(0,(ctx.night||1)-1)*GARY.appetitePerNight);const rate=appetiteBase*(this.p('appetite')||1)*(this.target.userData.garyEat||1)*lightMult*(this.p('eatCommit')||1);if(this.nextDecision<=0){this.nextDecision=1;ctx.onMunch&&ctx.onMunch(this)}const used=ctx.objects.consume(this.target,rate*dt,'raccoon',ctx.stats);this.fed+=used;if(used<=0||this.fed>this.fedGoal){this.state='leaving';this.target=new THREE.Vector3(-11,0,7)}}
    if(this.state==='leaving'){this.anchoredEat=false;this.setPose({tailUp:.5,lean:.25});if(this.moveToward(this.target,dt,ctx.objects.barriers,ctx)<.35){this.state='gone';this.active=false;this.root.visible=false;ctx.onGaryLeft(this)}}
  }
}
